[project]
name = "crmlite"
version = "0.1.0"
description = ""
authors = [
    {name = "meix",email = "meixz@mail.ru"}
]
requires-python = ">=3.14"
dependencies = [
    "django (>=6.1,<7.0)",
    "djangorestframework (>=3.18.0,<4.0.0)",
    "djangorestframework-simplejwt (>=5.5.1,<6.0.0)",
    "drf-spectacular (>=0.30.0,<0.31.0)",
    "django-filter (>=26.1,<27.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
